### ISSUE TITLE
Feature : open last result automatically if alone

### ISSUE THREAD

**Issue by owosoup** [MM2-0/Kvaesitso#1028]
Hex launcher has a search feature where it'll automatically open the resuling app if no other apps show up for your search terms. 

So if you search "f" you might get F-droid and Firefox, but if you search "Fir" you've already filtered everything and the last app remaining is Firefox. 

Since you already know the user wants to open Firefox, why not do it automatically?

**Comment by MM2-0** [comment]
> Since you already know the user wants to open Firefox, why not do it automatically?

Because a simple typo might send you of to a completely different app. And because because there is no definite point in time where the search can be considered as completed. Search providers are free to continuously update the search results. And they do, for example, the file search provider sends local file results first, but then a few seconds later it updates its own results with results from plugins and cloud drives.

Even if there was a mechanism for search providers to notify the UI "yep, I'm done, these are my final results, no more updates are coming", the UI would need to wait for the slowest provider to finish to make sure that there is really only one result, before it could launch anything. By that time, it is much faster to press the enter key, than it is to wait for the search to complete.

**Comment by owosoup** [comment]
I stand corrected. Nice explanation!
