### ISSUE TITLE
App list caching

### ISSUE THREAD

**Issue by Blastd** [MM2-0/Kvaesitso#142]
- Device: Samsung Galaxy S21 (SM-G991B)
- OS:     One UI 4.1 @ Android 12 (12 Aug patch)

Subject:
Feature suggestion

Description:
Loading the app list right now is pretty sluggish.
Currently I have 202 apps installed, which are a lot by itself, but I think that caching the list would help a lot reducing the lag that occurs each time I go back to the home screen.

**Comment by MM2-0** [comment]
The list itself is cached, the actual problem is the drawing of the icons itself (I think, I haven't been able locate the actual cause of this issue yet). Whenever a large amount of new icons appears on the screen, it starts lagging.

The good news is, I have rewritten the search results page to lay the items out lazily. This greatly improves the performance when you clear the search field and the number of installed apps should no longer affect the performance.

The bad news is that scrolling performance is now slightly decreased (especially when you scroll fast) because the icons are now laid out as you scroll. So it's a bit of a tradeoff and I hope I'll find the actual issue eventually but it's still a great improvement (I think).

Here is an experimental APK if you want to try it out (packed in a ZIP because Github does not allow APK uploads in issues):
[app-release.zip](https://github.com/MM2-0/Kvaesitso/files/9397498/app-release.zip)

Let me know what you think
