### ISSUE TITLE
Favorites bar bug at 5 icons

### ISSUE THREAD

**Issue by Tealk** [MM2-0/Kvaesitso#148]
My favorites bar is 5 icons wide and 2 icons high.

If I have only 4 icons in the favorites bar sorted manually and install a web app e.g. via Fennec the second row is hidden.

The web apps are added in pinned - automatically sorted and only when I add a second web app I see the second bar and then again the not pinned - frequently used icons.

**Comment by MM2-0** [comment]
Well, the intended behavior is that the last row of pinned items is filled with frequently used items. So there should not be a second row in the first place and the behavior with no second row at five pinned items is correct. The bug is, that there is a second row when you have less than 5 items pinned. But if I fix that now, I will probably break a lot of users config. So what I'll do to fix that is I'll make the favorites more configurable, adding an option to configure how many rows of frequently used items should be shown and a second option to disable the frequently used items altogether.

**Comment by MM2-0** [comment]
Will be implemented in 1.17
