### ISSUE TITLE
Android 13 themed icons on 12

### ISSUE THREAD

**Issue by julianfairfax** [MM2-0/Kvaesitso#167]
Is this something that can be done through a third-party launcher like this one, or is it really dependent on Android 13 itself with no workaround?

**Comment by MM2-0** [comment]
In theory, you probably could use some black magic to parse the XML files yourself but I'd rather not do this because it makes things way more complicated. I don't know anyway how many apps will actually make use of the themed icon feature.

I recommend to install [Lawnicons](https://github.com/LawnchairLauncher/lawnicons) as themed icons provider on Android 8-12.

**Comment by MM2-0** [comment]
This has been implemented now.
