### ISSUE TITLE
[Weather Widget] Add option to insert custom OWM key

### ISSUE THREAD

**Issue by Yen-Shock** [MM2-0/Kvaesitso#228]
### Issue
As the launcher indubitably increases in popularity, the preassigned free OpenWeatherMap key will probably break at some point because of excessive usage (I think one API key is limited to 1000 calls per day).

### Suggestion
**Include an option to insert a custom OWM API key.** 
I think this option can be hidden away somewhere deep down in the settings menu, so as to avoid clutter/overengineering (I am thinking of FairEmail as an extreme example).

**Comment by MM2-0** [comment]
Related: #227

**Comment by Yen-Shock** [comment]
I see, fair enough.^^
I only searched for "weather", "widget", etc., so my apologies for the duplicated issue.
Thanks for the immediate reaction!

**Comment by MM2-0** [comment]
I'm not using One Call API (because it is way more expensive than using two API calls for the other OWM APIs) so we have 1 000 000 free calls per month. This would allow about 700 users to use OWM as weather provider (if all of them are online all the time, 24 API calls per user per day). I have no stats about how close we are (maybe I should add some kind of telemetry to have at least a rough idea) but it's not unlikely that that number will be reached at some point.

Here are my thoughts about this:
- there are multiple weather providers built-in so the total number of users adds up
- the default weather provider is met.no which has a way more generous limit of 20 API calls per second. I don't know, how many people are actively changing their weather provider
- the actual number of API calls is lower because the weather doesn't need to be updated when the device is asleep (though I don't know if that's currently the case, someone has noticed that there are hourly wakelocks so I need to check that again)

**Comment by Yen-Shock** [comment]
Hmhmhmm, yes, that makes sense. Thanks for the info (seriously, not sarcastic).

My knowledge about the API issue was quite limited, and largely based on for instance Beocode's weather app, or OSS Weather by Akylas (and they by default require a custom OWM API key). Since I thought the API calls were much more limited, I tried not using your widget so much.

But maybe aside from the Yahoo Weather Widget (which is probably riddled with trackers), your widget is the most efficient and simply looks the best.

![_20221229_093123](https://user-images.githubusercontent.com/98064645/209888966-ebeb601f-1566-4d69-b37f-aa2c3233ad7e.JPG)

Come to think of it, could you please give me your opinion on the following?

- Would the above-shown image be achievable in the programming language which you use for Kvaesitso?
- Could this be done by a beginner (aka myself)?
- Would you be interested in such a pull-request?

Sorry for all those questions, but your launcher kind of ignited my interest in development.

**Comment by MM2-0** [comment]
>  Would the above-shown image be achievable in the programming language which you use for Kvaesitso?

Sure, everything is possible if you put some effort in it. That being said, I don't know if there is a library for that kind of chart, you might end up needing to draw it yourself.

> Could this be done by a beginner (aka myself)?

It's not trivia. You'd need to do all the math and the drawing by yourself. The math itself isn't that complicated but for a total beginner it's probably not the best introductory task


> Would you be interested in such a pull-request?

Honestly, I prefer my widget the way it is. The widget you posted is a bit too cluttered, for example you don't really see the current temperature at a glance, you need to do some maths in your head (unless I misunderstand how the widget works, which is also not a good sign)

**Comment by Yen-Shock** [comment]
Those are actually really good answers, including the last one. I guess I was a little overmotivated...^^

Alright then, I will just do the Japanese translation.

Vielen Dank für die Ehrlichkeit (ernst gemeint), und frohes Neues!
