### ISSUE TITLE
Nightly builds on F-Droid repo

### ISSUE THREAD

**Issue by Sir-Photch** [MM2-0/Kvaesitso#247]
Since Kvaesitso has a nightly-build CI, would it be possible to add these nightly builds to the MM2-0 F-Droid-repository?

**Comment by MM2-0** [comment]
Not in it's current setup but I need to rebuild that setup anyway at some point because Git is really not a good format to store binaries. When I do that, I'll try to include nightlies as well.

But keep in mind that nightly builds are not intended for daily use and that they might break without further notice.

**Comment by Sir-Photch** [comment]
> When I do that, I'll try to include nightlies as well.

Cool!

> But keep in mind that nightly builds are not intended for daily use and that they might break without further notice.

Of course. Still, there are other apps (Nextcloud, ...) with development versions on F-Droid too, so it would not be an unusual thing.

**Comment by MM2-0** [comment]
> Not in it's current setup but I need to rebuild that setup anyway at some point because Git is really not a good format to store binaries. When I do that, I'll try to include nightlies as well.

Done. Head over to https://fdroid.mm20.de to add the new repo.

**Comment by Sir-Photch** [comment]
Cool stuff!
