### ISSUE TITLE
SecurityException: Cannot resolve activity for unrelated profile 0

### ISSUE THREAD

**Issue by magujs** [MM2-0/Kvaesitso#301]
## Description

I don't know but next time i like add this

## Strack trace

```
java.lang.SecurityException: Cannot resolve activity for unrelated profile 0
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
	at android.os.Parcel.createException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2340)
	at android.os.Parcel.readException(Parcel.java:2282)
	at android.content.pm.ILauncherApps$Stub$Proxy.resolveActivity(ILauncherApps.java:1041)
	at android.content.pm.LauncherApps.resolveActivity(LauncherApps.java:718)
	at de.mm20.launcher2.search.data.LauncherAppDeserializer.deserialize(AppSerialization.kt:78)
	at de.mm20.launcher2.favorites.FavoritesRepositoryImpl.fromDatabaseEntity(FavoritesRepository.kt:209)
	at de.mm20.launcher2.favorites.FavoritesRepositoryImpl$getFavorites$$inlined$map$1$2.emit(Emitters.kt:78)
	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:5)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:24)
	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:1)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:142)
	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Channels.kt:12)
[18 lines truncated]
```

## Device info
APP.VERSION : 1.23.1<br>APP.VERSIONCODE : 2023031500<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 1625566115<br>VERSION.SDK.NUMBER : 30<br>BOARD : Gotron-GQ3096TF2<br>BOOTLOADER : unknown<br>BRAND : Ulefone<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : S7S68B7.GQU.Ulefone_EEA.HB.HJ.AZVKPVFMXPE.20210720.V3.02<br>FINGERPRINT : Ulefone/Power_Armor_13_EEA/Power_Armor_13:11/RP1A.200720.011/1625566115:user/release-keys<br>HARDWARE : mt6785<br>HOST : bs<br>ID : RP1A.200720.011<br>MANUFACTURER : Ulefone<br>MODEL : Power Armor 13<br>PRODUCT : Power_Armor_13_EEA<br>TAGS : release-keys<br>TIME : 1626748416000<br>TYPE : user

**Comment by JTriantafylos** [comment]
As an additional data point, I see the same crash in three different scenarios under GrapheneOS on a Pixel 7.

1. Install Kvaesitso into secondary user profile from the primary user profile by navigating to Settings > System > Multiple Users > [Secondary Profile Name] > Install available apps, and then selecting Kvaesitso. In this instance, Kvaesitso will crash immediately on launch.
2. Install Kvaesitso directly in a secondary user profile (via APK). Tap the "Hidden search results" button in the app drawer, and hit the edit (pencil) button in the "Hidden search results" popup, which will cause the crash to occur immediately.
3. Install Kvaesitso directly in a secondary user profile (via APK). Enter Kvaesitso settings and tap Debug > Clean up database. This will immediately cause the crash to occur.

Below is a guess as to what might be happening, with the caveat that I am not familiar with the Kvaesitso code base at all, or even Android development really.

Since this secondary profile is not a work (managed) profile, it seems like the `profiles` member of the `AppRepository` (https://github.com/MM2-0/Kvaesitso/blob/main/data/applications/src/main/java/de/mm20/launcher2/applications/AppRepository.kt#L44) is being populated from `UserManager#getUserProfiles()` which seems like it will include all user profiles "associated" with the current user (see [LauncherApps#getProfiles()](https://developer.android.com/reference/android/content/pm/LauncherApps#getProfiles()) and [UserManager#getUserProfiles](https://developer.android.com/reference/android/os/UserManager#getUserProfiles())).

It seems like there needs to be some sort of check in `AppSerialization.kt` (or maybe somewhere earlier in the chain) to ensure that the deserializer doesn't attempt to resolve an activity for an "unrelated" user, however I have no idea how that can be determined. Or maybe even doing something as simple as catching the `SecurityException` at the call to `resolveActivity()`?

Let me know if there is any other ways I can help get this solved.
Thanks.

**Comment by MM2-0** [comment]
Is there any reason you would install a launcher into a work profile? I didn't consider this scenario because usually users only install one launcher, in their main profile, and launch work profile related from there. What's the use case for this?

**Comment by JTriantafylos** [comment]
The way profiles work on GrapheneOS is more akin to having multiple installations of Android on your device. Profiles are entirely separated, meaning when you switch profiles its as if you picked up a different phone (other than the fact that profiles can send notifications to each other but that is not relevant).

Because of this, you end up needing to install Kvaesitso in each profile that you want to use it in.
