### ISSUE TITLE
Weird behavior in the icon picker option.

### ISSUE THREAD

**Issue by Donnnno** [MM2-0/Kvaesitso#302]
I wanted to change some icons with alts on my home screen, but noticed some strange behavior with the icon picker. 

Icons are duplicated, and the search function doesn't work fully. The search results are often incomplete, any idea what could cause this? 

![image](https://user-images.githubusercontent.com/31142286/227717013-c9217085-7bf4-4c84-8a3e-905036c05903.png)

Other launchers give an option to use the icon pack's build in picker. This might be a good thing to have too.

Thanks for the great launcher tho!

**Comment by Havock94** [comment]
I'm having the same issue when searching for Calendar icons in the Meeyo icon pack. 

![Screenshot_20230329-080939](https://user-images.githubusercontent.com/7635248/228441880-b8ce4c25-cf13-4eb3-8c2f-9eec971a0bff.jpg)

**Comment by Manan-31** [comment]
Same issue happening to me too. Sometimes it shows completely unrelated icons, sometimes when i search the full name of the app it doesn't show any results(App is present in the icon pack) and the custom calender icon is always blank. Maybe that's an issue because the calender icon changes daily?

Device: Redmi k50i
Android Version: 13 (MiUI 14)
Icon Packs Tried: Flora, Enix and Halo Icon Packs
Steps to reproduce: 
Step 1: Change Icon pack in settings.
Step 2: Edit icon for a singular app (Google calendar app)
Screenshots:
![Screenshot_2023-04-02-08-43-26-544_de mm20 launcher2 release](https://user-images.githubusercontent.com/70679272/229329209-b56a1cf4-261f-407a-a3dc-0eb0ef2871f8.jpg)
![Screenshot_2023-04-02-08-43-44-701_de mm20 launcher2 release](https://user-images.githubusercontent.com/70679272/229329213-5990b1d3-520d-4402-9aa3-da305bf7aff1.jpg)
![Screenshot_2023-04-02-08-43-54-097_de mm20 launcher2 release](https://user-images.githubusercontent.com/70679272/229329214-12ff2e40-185b-4d3e-a48c-4017d8a8d2d8.jpg)

I hope this helps.

**Comment by Donnnno** [comment]
Looks like it's fixed in the latest release! Thanks a lot :))
