### ISSUE TITLE
Grant permission problem

### ISSUE THREAD

**Issue by AdityaMH** [MM2-0/Kvaesitso#321]
Always ask grant permission to allow "everything" like notification acess,  contact, etc. Even allowing grant in first install

Fixed when reboot phone. But bug going same again after 10 minutes.

**Comment by exstntlmsnthrp** [comment]
Can you please provide more information? For example your phone brand/model, Android version, and app version? Can you see anything in the app logs or can you post them here?

I've been using this app since the first couple of months it was posted on GitHub and have never seen or heard of this problem and wonder if it's possibly related to the phone or Android version. 

However, there are a few steps you could try as well in your phone settings. 

1. Select Apps > Kvaesitso > Permissions

Then enable all permissions that you feel are important. 

Another thing you could try, though not required, is select the three dots in upper right corner and allow those permissions as well.

Under settings, you can also go to Accessibility and enable Kvaesitso as well. 

Maybe these things will help you.

**Comment by AdityaMH** [comment]
> Can you please provide more information? For example your phone brand/model, Android version, and app version? 
MIUI 12, Android 10, 1.23.1

> Can you see anything in the app logs or can you post them here?
Where i can find that log?
 
> However, there are a few steps you could try as well in your phone settings.
> 
> 1. Select Apps > Kvaesitso > Permissions
> 
> Then enable all permissions that you feel are important.
> 
> Another thing you could try, though not required, is select the three dots in upper right corner and allow those permissions as well.
> 
> Under settings, you can also go to Accessibility and enable Kvaesitso as well.
> 
> Maybe these things will help you.

No use, it's dont effect to my phone.

**Comment by exstntlmsnthrp** [comment]
That's rather bizarre. I'm not an Android developer, so you may have to wait until @MM2-0 responds to see what they have to say about your problems. It seems like a permissions issue, but beyond that I'm not sure at the moment.

You can find the logs for Kvaesitso in: Settings > Debug > Logs

If you can either copy them in a reply or link to another place where they can be viewed, it may help the developer answer your problems.

**Comment by AdityaMH** [comment]
[kvaesitso-log-2023-04-05-132101.zip](https://github.com/MM2-0/Kvaesitso/files/11155941/kvaesitso-log-2023-04-05-132101.zip)

**Comment by MM2-0** [comment]
I suspect the system is killing the notification listener service as part of the oem's  battery "optimizations". Try this: https://dontkillmyapp.com/, maybe it helps.

**Comment by exstntlmsnthrp** [comment]
> I suspect the system is killing the notification listener service as part of the oem's  battery "optimizations".

This completely makes sense. 👍🏾

**Comment by AdityaMH** [comment]
Bit strange, but solved by change background setting and choose "disable miui battery saving".

**Comment by MM2-0** [comment]
> Bit strange, but solved by change background setting and choose "disable miui battery saving" in app setting. now, kvaesitso become my main launcher again.

This makes perfect sense to me, thanks for confirming, I will add a page to the docs.
