### ISSUE TITLE
Alarm reminder uses only minutes

### ISSUE THREAD

**Issue by BrightDV** [MM2-0/Kvaesitso#38]
Hello,

If the alarm is set to more than an hour, but ended for example in 1h06, it will show the reminder `Alarm in 6 minutes` instead of `Alarm in 1h06 minutes` or even no reminder, see the screenshots below.

<img src="https://user-images.githubusercontent.com/92821484/157086324-4490ed5d-632d-4135-8e14-1ceb57e32890.png" alt="screen for further info" height="200"><img src="https://user-images.githubusercontent.com/92821484/157086336-fec7e87f-2a93-4242-9c2d-5d2ea043c678.png" alt="screen for further info" height="100">

**Comment by MM2-0** [comment]
It's not supposed to show alarms that are that far in the future per default... have you disabled all the other options (date, music, battery)? Even if I disable them, it shows `In 1 hour` for me, so it's correctly rounded down to the full hour. It would surprise me if there was a bug in the formatting function since that function is provided by the Android framework. Are you sure there isn't any other alarm scheduled? What alarm app are you using?

**Comment by BrightDV** [comment]
Oh, I know, it is due to the calendar event, sorry...
