### ISSUE TITLE
[Enhancement] Hide keyboard after opening an app

### ISSUE THREAD

**Issue by BrightDV** [MM2-0/Kvaesitso#40]
Hello,

In the latest version, the keyboard can be shown when going to the drawer.
However, while opening an app, the keyboard don't disappear.
It would be nice to have the keyboard disappearing when opening an app, because for some apps with a big loading time, it's a little annoying. However, I don't know how difficult would it be to add such a feature.

Here is an example with the ProtonMail app :
<img src="https://user-images.githubusercontent.com/92821484/158022010-4f2f5cde-a718-4afc-8b95-d0c7beec4523.png" alt="screenshot of the example" height=300>

**Comment by MM2-0** [comment]
I have modified the keyboard behavior: starting an app will now hide the keyboard, returning to home will reopen the keyboard (only if Automatically open keyboard is enabled and the search is still open). This is a behavior change since it will not remember the keyboard state anymore so the overall behavior should be more consistent.
