### ISSUE TITLE
[feature request] Support to Proton Calendar

### ISSUE THREAD

**Issue by jontaix** [MM2-0/Kvaesitso#44]
Since I don't use Stock calendar nor Google Calendar, nothing appears in the calendar widget. Is it possible to add support for Proton Calendar (from ProtonMail)?

**Comment by MM2-0** [comment]
I'm afraid that this is not possible. They don't use the Android calendar provider to store their calendar data so there is no way for other apps to access them. I think this is [intentional](https://protonmail.com/blog/calendar-android-beta/), to protect their user's privacy so I guess we're out of luck here.

**Comment by jontaix** [comment]
no problem. 😔
I suspected it wouldn't be possible.
