### ISSUE TITLE
Launcher home screen redesign

### ISSUE THREAD

**Issue by ansarimohammed422** [MM2-0/Kvaesitso#46]
My issue is related to some unusability of home screen

Issues:-

1. I cant access the the notification of my phone with one 
     hand because the swipe down gesture brings 
     application drawer

2. I also cant access search bar with one hand because its 
     too far upwards

3. I also cant bring app icons to home screen every time i 
     have to open an app its by either searching or with app 
     drawer 

Solutions:-

1. Related to notification make swipe down gesture to 
     bring down notification panel

2. Move search bar at the bottom for easier access and 
     also create bock above search bar for favourite 
     application icons

3. And add home screen icons support so we can access 
    apps easily.

Please see on to it and give your feedback.

**Comment by MM2-0** [comment]
So you're basically suggesting that I completely rebuild the layout of my launcher? I have thought about adding alternative layout options in the future but I haven't decided yet what kind of layouts I will add and if it's worth the extra complexity this will introduce. One idea was a pager (home screen on the left page, search on the right page) which would free up the swipe down gesture for notifications, possibly with the search bar on the bottom so I think that would solve most of your issues. I can't promise that I add this very soon though because I probably need to do some other things first.

Additional notes regarding your issues: 

1. I've never had this problem because I always use the fingerprint swipe gesture to open notifications. I guess you don't have a fingerprint scanner on the back of your phone?
2. You can enable the option to auto show the keyboard so you'll never have to actually tap on the search bar. However since this has been requested quite a few times now (see #39 ) so I'm planning to add this in the future.
3. I plan to add a favorites widget eventually (see #30 ), and maybe also an option to show a row of favorites in the clock widget (instead of the date) but other than that I don't plan to add icons to the home screen. If you want that, you should use one of the countless other launchers there are out there.

**Comment by JakeHL** [comment]
I completely agree that this launcher should not support icons on the home screen in the traditional sense. Only showing favorites would just be a really nice to have feature, however. I'm excited for that!

**Comment by MM2-0** [comment]
I have some good news for you then: it's already out! (v1.8.0)
