### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#47]
## Description

Unfortunately I don't have real steps to reproduce the issue, pretty much every morning when I take the phone (that has been on and either connected or not, this time it wasn't), I get a launcher crash (this one) or exception (Unable to resolve api.openweathermap.org).
I hope this helps.

## Strack trace

```
java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.os.Bundle instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/0x9. Make sure other views do not use the same id.
	at android.view.View.onRestoreInstanceState(View.java:20918)
	at android.view.View.dispatchRestoreInstanceState(View.java:20890)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4011)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
	at android.view.ViewGroup.dispatchRestoreInstanceState(ViewGroup.java:4017)
[19 lines truncated]
```

## Device info
APP.VERSION : 1.7.1-20220324<br>APP.VERSIONCODE : 2022032400<br>LAUNCHER.APP : android<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 11<br>VERSION.INCREMENTAL : 2202182344<br>VERSION.SDK.NUMBER : 30<br>BOARD : kona<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : KB2003_15_220218<br>FINGERPRINT : OnePlus/OnePlus8T_EEA/OnePlus8T:11/RP1A.201005.001/2202182344:user/release-keys<br>HARDWARE : qcom<br>HOST : rd-build-72<br>ID : RP1A.201005.001<br>MANUFACTURER : OnePlus<br>MODEL : KB2003<br>PRODUCT : OnePlus8T_EEA<br>TAGS : release-keys<br>TIME : 1645199356000<br>TYPE : user

**Comment by MM2-0** [comment]
I have no idea what could cause this. You are not the first who has this issue. It doesn't seem to happen on Android 12; all the reports I received so far were on Android 11. I can't reproduce it (my main device is on Android 12 and I can't reproduce it on the emulator). I assume it has something to do with the widgets (because the widgets are the only part of the UI that still use the old Android views) but I don't know how to fix this. Do you use any third party app widgets or just the built-in ones?

If I understand correctly you can't reproduce it either, it just happens randomly after you haven't used the device for a longer time?

About the second thing: exceptions are usually not a problem and can be safely ignored. They can be helpful if something doesn't work as expected. In this case I'd assume the launcher attempted to fetch new weather data while the phone was not connected to the internet so it failed. Not a big deal, it will try again later and hopefully succeed eventually. If your weather widget is still up-to-date, you can safely ignore these exceptions.

**Comment by glemco** [comment]
> If I understand correctly you can't reproduce it either, it just happens randomly after you haven't used the device for a longer time?

Yes exactly, also it isn't a big problem, just pressing the home key brings me back as if nothing happened. The only mildly annoying thing is that it brings me to the stock launcher (Oneplus) and once I press the home key it asks me to select which one I want as default.

I am using a custom widget (from OpenTasks) and all built-in widgets.

Since the trace doesn't help you, I'd just ignore this crash as it isn't a big problem after all..

> About the second thing: exceptions are usually not a problem and can safely be ignored.

Thanks for the explanation, I'll not pay attention to it then!

**Comment by MM2-0** [comment]
I have rewritten the widget column in version 1.8.0, please report back whether this issue persists.

**Comment by glemco** [comment]
The last time was the 29th of March (weirdly it happened only on odd-numbered days), but never again since then. I'll let you know if it happens once more
