### ISSUE TITLE
Background blur not working

### ISSUE THREAD

**Issue by kaibagley** [MM2-0/Kvaesitso#590]
Hey guys,
On GrapheneOS AOSP version 14 (latest), having background enabled doesn't actually blur anything. There is no difference between having it on or off.

Also, thanks for making such a good app!

**Comment by exstntlmsnthrp** [comment]
This has already been mentioned in #112.

**Comment by kaibagley** [comment]
Indeed, issue is closed however so thought I'd start a new one

**Comment by exstntlmsnthrp** [comment]
I can confirm the wallpaper blur also does not work on stock Android. I checked the logs and didn't find anything relevant and cleaned up the database and nothing changed.

**Comment by MM2-0** [comment]
It's fixed on my Pixel 8, but on my Pixel 2 XL (on which it was working flawlessly before), it now lags a lot when blur is enabled. Since the Pixel 2 XL isn't supposed to support blur in the first place (I had to modify a system prop to enable it), this would be acceptable for me, but I wonder if it's noticable on other devices as well?
