### ISSUE TITLE
Support to add apps on homescreen 

### ISSUE THREAD

**Issue by arnabs542** [MM2-0/Kvaesitso#618]
Please give a option to add icons on the homescreen with dock support like nova launcher. Thanks.

**Comment by arnabs542** [comment]
@exstntlmsnthrp hi would you please tell the process on how to pin my favourite apps to the homescreen. thanks in advance

**Comment by arnabs542** [comment]
Got the solution from https://kvaesitso.mm20.de/docs/user-guide/faq/. Thanks

**Comment by exstntlmsnthrp** [comment]
Sorry for the delay. Did that work for you?

I only ask, because I tried implementing it to send you a screenshot but it didn't work for me. 😅😅 So I have to figure that out and possibly report a bug. 

If you didn't see it, you can also increase the number of columns and rows in your favourites to increase the number of apps.
