### ISSUE TITLE
Weather widget seems to not recongnize changes in config.

### ISSUE THREAD

**Issue by shruuub** [MM2-0/Kvaesitso#62]
Hello. So, when changing the Weather provider (for example from the german to owm), the widget does not recognize the changes. Restarting, clearing cache or removing and adding the widget does nothing, the only option is deleting the data and reconfiguring everything.

**Comment by MM2-0** [comment]
Changing the weather provider (or the location) should force an update. Could you go to Settings > Debug > Crash Reporter check if there are any suspicious exceptions related to the weather?
Also, have you granted location permission to the launcher? If not, you'll need to reconfigure the location settings after a provider change because these settings are stored per provider.

**Comment by shruuub** [comment]
> Changing the weather provider (or the location) should force an update immediately. Could you go to Settings > Debug > Crash Reporter check if there are any suspicious exceptions related to the weather?
> Also, have you granted location permission to the launcher? If not, you'll need to reconfigure the location settings after a provider change because these settings are stored per provider.

I forgot to mention that there's nothing in the logs, but yes, setting the location manually again fixes it.
