### ISSUE TITLE
File manager not opening in the right directory 

### ISSUE THREAD

**Issue by glemco** [MM2-0/Kvaesitso#63]
While searching for files and directory, the launcher shows them correctly in the search results, however if trying to open a folder from there, the file manager opens in the storage root, independently on the searched folder.
I could only get it open with Material Files (other file manager I tried probably don't even expect the intent), it could even be a problem in the file manager, but it works fine in combination with Synchthing-Fork (for a very similar use case).
Am I missing something?
Thanks in advance

**Comment by MM2-0** [comment]
It's a bit tricky. There isn't really an official standard about how to open a directory so each file manager could potentially have it implemented differently (or not at all). There isn't even a real standard for which MIME type to use (some apps use `inode/directory`, some use `resource/folder`, Android seems to prefer `vnd.android.document/directory`. There is the AOSP file manager, DocumentsUI, which we could consider the reference implementation of a file manager for Android, but even after investigating its source code I haven't found a way to open a specific directory in DocumentsUI. That being said, I don't know if there is any file manager at all that works with the launcher's current implementation. Since one is better than zero and Material Files is one of the most popular FOSS file manager app, I'll change it to make it work with Material Files.

**Comment by MM2-0** [comment]
Fixed in fc32025

**Comment by glemco** [comment]
I imagined that, thanks for the quick fix!
