### ISSUE TITLE
Lag when swiping down for app drawer

### ISSUE THREAD

**Issue by ebanDev** [MM2-0/Kvaesitso#672]
[kvaesitso-log-2024-01-22-142646.txt](https://github.com/MM2-0/Kvaesitso/files/14010659/kvaesitso-log-2024-01-22-142646.txt)

[video](https://github.com/MM2-0/Kvaesitso/assets/57091497/c5b8f55d-a6bf-4b48-a5b7-cffc11fefef4)

Hello ! :)

When I swipe down to open the app drawer the animation lags as you can see on the video attached. I also attached the logs, here are my device infos : 

Device : Google Pixel 6a
Android version : 14
Android distribution : GrapheneOS
GrapheneOS version : latest as of now, [2024011600](https://grapheneos.org/releases#2024011600)

Best,
Eban

**Comment by theuser18** [comment]
Duplicate of #613

**Comment by ebanDev** [comment]
Im gonna try that, thank you and sorry for the duplicate!

**Comment by kuvaldini** [comment]
@ebanDev  did that workaround help you?

**Comment by ebanDev** [comment]
> @ebanDev  did that workaround help you?

Yeah I tried and it works ! Thank you :)

**Comment by Greysys** [comment]
> Duplicate of #613
> 
> Try the temporary workaround [here](https://github.com/MM2-0/Kvaesitso/issues/613#issuecomment-1841316010)

I'm not able to use that workaround, because grapheneOS does not automatically optimise apps for me (or at least it doesn't tell me when it does, like the workaround suggests. The result is I get the launcher working smoothly for some minutes, then soon after it is laggy again. Is there a setting to tell grapheneOS to optimise my apps that I'm unaware of?

**Comment by theuser18** [comment]
Newer versions of Graphene optimize apps on startup after substantial updates. This should be happening to you 1-2 times a month.

-------- Original Message --------
