### ISSUE TITLE
Sort by alphabetical should prioritize apps that START with the search term. 

### ISSUE THREAD

**Issue by Schweiger-Jacob** [MM2-0/Kvaesitso#676]
I find it bizarre that it doesn't. There should be an option to enable this behavior as that's the way that start menus typically work because. If I start typing c I should not be getting apps that start with a as the first suggestion.

**Comment by Zerodya** [comment]
Agree. It should at least be a toggle so that we can use it with both Alphabetic and Usage order. I use Usage and if I type 'c' (for example to open the clock) I get a different app first that doesn't start with 'c' but contains it, just because I use it more often. 
KISS launcher has this behavior and it's the one thing that makes its search so good imo.

**Comment by MayushKumar** [comment]
Any updates on this? Are there any plans for this to be implemented?
