### ISSUE TITLE
Random error

### ISSUE THREAD

**Issue by Cameo007** [MM2-0/Kvaesitso#967]
## Description

*Please provide as many information about the crash as possible (What did you do before the crash happened? Steps to reproduce?)*
I did nothing and Kvaesitso did not crash but I saw this log.

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@351fdd, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : A536BXXSBEXF3<br>VERSION.SDK.NUMBER : 34<br>BOARD : s5e8825<br>BOOTLOADER : A536BXXSBEXF3<br>BRAND : samsung<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : UP1A.231005.007.A536BXXSBEXF3<br>FINGERPRINT : samsung/a53xnaeea/a53x:14/UP1A.231005.007/A536BXXSBEXF3:user/release-keys<br>HARDWARE : s5e8825<br>HOST : SWDK6518<br>ID : UP1A.231005.007<br>MANUFACTURER : samsung<br>MODEL : SM-A536B<br>PRODUCT : a53xnaeea<br>TAGS : release-keys<br>TIME : 1719217236000<br>TYPE : user

**Comment by profitrollgame** [comment]
Happens to me as well since version 1.32.0

## Strack trace

```
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Object kotlinx.coroutines.sync.MutexImpl.lock(java.lang.Object, kotlin.coroutines.Continuation)' on a null object reference
	at de.mm20.launcher2.profiles.ProfileManager.access$refreshProfiles(ProfileManager.kt:69)
	at de.mm20.launcher2.profiles.ProfileManager$2.invokeSuspend(ProfileManager.kt:64)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:9)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:111)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:98)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@f40b3f8, Dispatchers.Default]

```

## Device info
APP.VERSION : 1.32.0<br>APP.VERSIONCODE : 2024071900<br>APP.SIGNATURE : rx1fSnL7r5/OMoFC0e1KPqTndXQ=<br>LAUNCHER.APP : de.mm20.launcher2.release<br>TIMEZONE : Europe/Berlin<br>VERSION.RELEASE : 14<br>VERSION.INCREMENTAL : 2121<br>VERSION.SDK.NUMBER : 34<br>BOARD : msmnile<br>BOOTLOADER : unknown<br>BRAND : OnePlus<br>CPU_ABI : arm64-v8a<br>CPU_ABI2 : <br>DISPLAY : AP1A.240405.002.A1<br>FINGERPRINT : OnePlus/OnePlus7TPro/OnePlus7TPro:12/SKQ1.211113.001/Q.202303230244:user/release-keys<br>HARDWARE : qcom<br>HOST : instance-20240205-0123<br>ID : AP1A.240405.002.A1<br>MANUFACTURER : OnePlus<br>MODEL : HD1911<br>PRODUCT : OnePlus7TPro<br>TAGS : release-keys<br>TIME : 1713184571000<br>TYPE : userdebug
