### ISSUE TITLE
Switch to switch between private and work profile apps is gone

### ISSUE THREAD

**Issue by ErikSteiner** [MM2-0/Kvaesitso#989]
A few days ago, I noticed that the switch for apps for the private or work profile can no longer be found at the top. The apps are now below each other. First comes the block of private apps and then the block of work profile apps. I also noticed that there is a lock symbol next to the title of the work profile apps. I am not sure, about its function.

I suspect that the apps of the profiles were arranged one below the other by a gesture. However, I'm not sure. A screenshot of how it used to look and how I would like it to look again is attached.
![1000001656](https://github.com/user-attachments/assets/3ff73f33-5b03-4be9-af76-f888c8b660f8)

**Comment by MM2-0** [comment]
The arrangement has been changed for several reasons:
- there are now potentially three profiles (personal, work, and private) and the space was to constained for three tabs in one row
- tabs imply a swipe gesture to switch between tabs, which wasn't possible, so using tabs here could lead to confusion and frustration
-  with the list of work profiles often being shorter than the viewport, there was a bug that lead to a layout state where after switching to the work profile, the search bar was still scrolled out of view but you could't bring it back because you couldn't scroll any more due to the list being too short

The new layout solves all of these issues and leaves enogh space to display extra actions for each profile – such as the lock, which pauses the work profile and locks it. If you have set up a screen lock, you'll need to enter it again in order to unlock the profile.

**Comment by kubesteak** [comment]
I second the request for reversion to prior layout. Having to scroll all the way to the bottom every time I need to get to my work profile is time consuming and unintuitive.

**Comment by ErikSteiner** [comment]
Unfortunately, I have to say that I'm not happy with the decision. To put it mildly. For example, I have installed all Google apps in the Work profile and all F-Droid apps in the normal profile. For context: I use MicroG. The fact that I can no longer tap on Work for the Somfy app, for example, but have to scroll down a long list. Many launchers that don't have the category view, as was the case with Kvaesitso, have been permanently removed from my smartphone. That's simply inefficient for me.

So, now let's take a more constructive approach:
- how about having the two buttons again, but without the swipe gesture. Simple buttons.
  - if there are two profiles, two buttons
  - if three profiles or more, then ONE button as a dropdown from which I can select the profile
- a legacy setting that reactivates the previous way, with reference to the problems described

**Comment by MM2-0** [comment]
> BTW. Quickstep Launcher from AOSP may have the same problem. It would be interesting, how they solved it.

Pixel launcher embeds the private space profile at the bottom of the personal profile:

<img src="https://github.com/user-attachments/assets/c40ed09f-45d9-43d0-a191-878da5a15e0b" width=300>

But I disagree with that design, because both private space and work profile are separate workspaces that you can install apps to. So conceptionally, they should be on the same hierarchy level. You can't have a private space within your work profile.

Oh, and also, the "pause work profile" button feels a bit out of place. It's way too prominent and it seems like it has been added as an afterthought:
<img src="https://github.com/user-attachments/assets/7884395e-4fe9-4dd0-81b7-873c0f104bbb" width=300>

But there are instances where Android displays all three profiles in one row, notably in the share menu:
<img src="https://github.com/user-attachments/assets/72100823-0935-4e75-b42d-4612ccbedb93" width=300>
But then there is the problem that when you set your system language to Ukrainian (and possibly other languages), it doesn't fit:

<img src="https://github.com/user-attachments/assets/e91a30ba-1d96-4caf-8d36-a964303ffc14" width=300>

(this is exactly what I was worried about and why I changed it; some localizations just need wider labels that don't work well with the constrained space)

**Comment by MM2-0** [comment]
> but have to scroll down a long list is annoying

Or you could, you know, use the search. Or pin it to the favorites section, if you use it that frequently. But I get your point.

> So, now let's take a more constructive approach:
>
> - how about having the two buttons again.
>  - if there are two profiles, two buttons
>  - if three profiles or more, then ONE button as a dropdown from which I can select the profile

And where do we put the lock / unlock buttons?

> a legacy setting that reactivates the previous way, with reference to the problems described

No. I can't add settings for everything. Better find a design that works for everyone.

> add buttons again, but they work as a jump point, to jump down to the specific section. That way, you could use the new layout, but it saves us scrolling time. 

This might be the most sensible approach. Combined with an alphabet like #201 suggests. But also the most difficult to implement.

**Comment by juzim** [comment]
Would it be possible to add a default "work' tag to all work profile apps? This way I could pin the tag to the favorites bar and have all apps available with one click.
Of course we can tag them by hand of course but this might mirror the requested behavior.

**Comment by Techognito** [comment]
Another suggestion, could we put work apps at the top?

Or have a setting for changing the module order?

**Comment by thecoldsea** [comment]
- Please make an option to list all apps on one simple page. Main profile apps first then work profile apps. 
- Also make it possible to switch between Personal and Work profile app categories with a swipe while the app drawer is open.

**Comment by uestueab** [comment]
> * Also make it possible to switch between Personal and Work profile app categories with a swipe while the app drawer is open.

Is this implemented? Would be a big game changer for me
